workspace = { members = ["lib"] }
[package]
name = "rustycommits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_lint = {path = "lib"}
